"""empty message

Revision ID: c4e7f3ecc672
Revises: c570078b9d48
Create Date: 2020-03-15 15:11:13.437752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4e7f3ecc672'
down_revision = 'c570078b9d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker', 'enterprise_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeker', sa.Column('enterprise_name', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
