"""empty message

Revision ID: c570078b9d48
Revises: 
Create Date: 2020-03-15 15:10:26.658493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c570078b9d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterpriser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('enterprise_name', sa.String(length=128), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seeker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('enterprise_name', sa.String(length=128), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_publisher_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('job_category', sa.String(length=32), nullable=False),
    sa.Column('workplace', sa.String(length=64), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_publisher_id'], ['enterpriser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('seeker')
    op.drop_table('enterpriser')
    # ### end Alembic commands ###
